### ISSUE TITLE
Can you compile older versions of webrtc?

### ISSUE THREAD

**Issue by zuowanbushiwo** [godotengine/webrtc-actions#2]
Hi 
     Thank you so much for this project, this project helped save a lot of time. 
     Can this project compile older versions of webrtc? For example 2012, 2014 webrtc.

thanks！

**Comment by Faless** [comment]
Likely no, google changes the build system almost on every release, so it
usually needs some manual work to build a different version.
I would also advice against using such old release as they are likely to
have security issues.

**Comment by zuowanbushiwo** [comment]
Thanks
